#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" \
  apk add --no-cache \
    libpulse \
    mesa-demos \
    mesa-dri-gallium \
    supertuxkart

buildah config \
  --cmd '[]' \
  --entrypoint '["supertuxkart"]' \
  "$container"

if ! buildah run -t "$container" -- supertuxkart --version; then
  printf 'ERROR: supertuxkart not installed\n' >&2
  exit 1
fi

buildah commit "$container" supertuxkart
