#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah copy "$container" \
  https://codeberg.org/nsxiv/nsxiv/raw/branch/master/etc/nsxiv.1 \
  https://github.com/andmarti1424/sc-im/raw/main/src/sc-im.1 \
  https://github.com/asciidoctor/asciidoctor/raw/main/man/asciidoctor.1 \
  https://github.com/jgm/pandoc/raw/main/man/pandoc.1 \
  https://github.com/mawww/kakoune/raw/master/doc/kak.1 \
  https://github.com/mcpcpc/kirc/raw/master/kirc.1 \
  https://github.com/openscad/openscad/raw/master/doc/openscad.1 \
  'https://sourceforge.net/p/fuse-emulator/code/HEAD/tree/trunk/fuse/man/fuse.1?format=raw' \
  /usr/local/share/man/man1

buildah copy "$container" \
  https://github.com/mupen64plus/mupen64plus-ui-console/raw/master/doc/mupen64plus.6 \
  https://github.com/supertuxkart/stk-code/raw/master/doc/supertuxkart.6 \
  /usr/local/share/man/man6

buildah run "$container" -- \
  apk add --no-cache \
    aspell-doc \
    bash-doc \
    bat-doc \
    binutils-doc \
    bmon-doc \
    cbonsai-doc \
    chafa-doc \
    clifm-doc \
    cmatrix-doc \
    cmus-doc \
    ctags-doc \
    curl-doc \
    dillo-doc \
    dropbear-doc \
    dunst-doc \
    eza-doc \
    ffmpeg-doc \
    file-doc \
    fontforge-doc \
    fortune-doc \
    gcc-doc \
    gimp-doc \
    git-doc \
    gnupg-doc \
    gnuplot-doc \
    graphicsmagick-doc \
    htop-doc \
    hunspell-doc \
    iftop-doc \
    imagemagick-doc \
    inkscape-doc \
    isync-doc \
    jq-doc \
    ledger-doc \
    less \
    lf-doc \
    make-doc \
    man-pages \
    man-pages-posix \
    mandoc \
    mandoc-apropos \
    mandoc-doc \
    mblaze-doc \
    mc-doc \
    mpc-doc \
    mpd-doc \
    mpv-doc \
    mupdf-doc \
    ncmpcpp-doc \
    ncurses-doc \
    nnn-doc \
    nodejs-current-doc \
    notmuch-doc \
    openssl-doc \
    patch-doc \
    qemu-doc \
    redshift-doc \
    ripgrep-doc \
    rsvg-convert-doc \
    rsync-doc \
    ruby-doc \
    shellcheck-doc \
    sl-doc \
    s-nail-doc \
    socat-doc \
    stellarium-doc \
    tmux-doc \
    vifm-doc \
    vimb-doc \
    vis-doc \
    w3m-doc \
    xsel-doc \
    yt-dlp-doc

buildah config \
  --cmd '[]' \
  --entrypoint '["man"]' \
  --env MANPAGER='less -R --use-color -Dd+b -Dug -DSky -DEwr -DPg' \
  "$container"

buildah commit "$container" man
