#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache darkhttpd

buildah config \
  --cmd '[]' \
  --entrypoint '["darkhttpd"]' \
  "$container"

if ! buildah run -t "$container" -- /bin/sh -c 'command -v darkhttpd' >/dev/null
then
  printf 'ERROR: darkhttpd not installed\n' >&2
  exit 1
fi

buildah commit "$container" darkhttpd
