#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" \
  apk add --no-cache \
    mesa-demos \
    mesa-dri-gallium \
    stellarium

buildah config \
  --cmd '[]' \
  --entrypoint '["stellarium"]' \
  "$container"

# NOTE: This verification doesn't work because stellarium starts the GUI for
# an instant (splash screen) before printing the version to stdout.
# if ! buildah run -t "$container" -- stellarium --version; then
  # printf 'ERROR: stellarium not installed\n' >&2
  # exit 1
# fi

buildah commit "$container" stellarium
