#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    htop

buildah config \
  --cmd '[]' \
  --entrypoint '["htop"]' \
  "$container"

if ! buildah run -t "$container" -- htop --version; then
  printf 'ERROR: htop not installed\n' >&2
  exit 1
fi

buildah commit "$container" htop
