#!/bin/sh

container=$(buildah from --pull debian:stable-slim)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  sh -c 'apt update && \
    apt install --no-install-recommends --yes \
      caveexpress \
      cavepacker \
      libgl1-mesa-dri \
      libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*'

buildah config \
  --cmd '[]' \
  --entrypoint '["/usr/games/caveexpress"]' \
  "$container"

buildah commit "$container" caveexpress
