#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    iftop

buildah config \
  --cmd '[]' \
  --entrypoint '["iftop"]' \
  "$container"

if ! buildah run -t "$container" -- iftop -h; then
  printf 'ERROR: iftop not installed\n' >&2
  exit 1
fi

buildah commit "$container" iftop
