#!/bin/sh

if test $# -eq 0; then
  printf 'filename> '
  read -r filename
  set -- "$filename"
fi

while test $# -gt 0; do
  if test -f "$1"; then
    case "$1" in
      *.tar.bz2|*.tb2|*.tbz|*.tbz2|*.tz2) tar xjf "$1"   ;;
      *.tar.gz|*.taz|*.tgz|*.tpz)         tar xzf "$1"   ;;
      *.tar.lz|*.tar.lzma|*.tlz)          tar xaf "$1"   ;;
      *.tar.xz|*.txz)                     tar xJf "$1"   ;;
      *.tar.Z|*.tZ|*.taZ)                 tar xZf "$1"   ;;
      *.tar)                              tar xf "$1"    ;;
      *.gz)                               gunzip "$1"    ;;
      *.bz2)                              bunzip2 "$1"   ;;
      *.zip)                              unzip "$1"     ;;
      *.Z)                                gzip -d "$1"   ;;
      *.rar)                              bsdtar xf "$1" ;;
      *) echo "'$1' can't be extracted with this script." >&2 ;;
    esac
  else
    echo "'$1' does not exist." >&2
  fi
  shift
done
