#!/bin/sh

container=$(buildah from --pull debian:stable-slim)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  sh -c 'apt update && \
    apt install --no-install-recommends --yes \
      ca-certificates \
      curl \
      unzip'

buildah run "$container" -- \
  sh -c 'curl -fsSL https://bun.sh/install | bash'

buildah run "$container" -- \
  sh -c 'apt purge --yes ca-certificates curl unzip && \
    apt autoremove --yes && \
    rm -rf /var/lib/apt/lists/*'

# shellcheck disable=SC2016
buildah config \
  --cmd '[]' \
  --entrypoint '["bun"]' \
  --env PATH='/root/.bun/bin:$PATH' \
  "$container"

if ! buildah run -t "$container" -- bun --version; then
  printf 'ERROR: bun not installed\n' >&2
  exit 1
fi

buildah commit "$container" bun
