#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache cmus

# Configure cmus by appending to the default configuration instead of the user
# configuration to allow for using the local directory for maintaining state.
# Disable mpris to remove startup warning (mpris doesn't work in the container).
buildah run "$container" -- \
 sh -c 'printf "colorscheme dracula\nset mpris=false\n" >> /usr/share/cmus/rc'

buildah config \
  --cmd '[]' \
  --entrypoint '["cmus"]' \
  "$container"

if ! buildah run -t "$container" -- cmus --version; then
  printf 'ERROR: cmus not installed\n' >&2
  exit 1
fi

buildah commit "$container" cmus
