#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    exa \
    file

buildah config \
  --cmd '[]' \
  --entrypoint '["exa"]' \
  "$container"

if ! buildah run -t "$container" -- exa --version; then
  printf 'ERROR: exa not installed\n' >&2
  exit 1
fi

buildah commit "$container" exa
