#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    transmission-remote

buildah config \
  --cmd '[]' \
  --entrypoint '["transmission-remote"]' \
  "$container"

if ! buildah run -t "$container" -- transmission-remote --version; then
  printf 'ERROR: transmission-remote not installed\n' >&2
  exit 1
fi

buildah commit "$container" transmission-remote
