#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    dropbear \
    dropbear-convert

buildah config \
  --cmd '[]' \
  --entrypoint '["dropbear"]' \
  "$container"

buildah run "$container" -- \
  sh -c 'printf "\nWelcome toͪ ͣdͬrͩopͨbͦeͬaͤr!\n\n" > /etc/motd'

if ! buildah run -t "$container" -- dropbear -V; then
  printf 'ERROR: dropbear not installed\n' >&2
  exit 1
fi

buildah commit "$container" dropbear
