#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk --no-cache add \
    ca-certificates \
    dillo

buildah config \
  --cmd '[]' \
  --entrypoint '["dillo"]' \
  "$container"

buildah copy "$container" config /root/.dillo/

if ! buildah run -t "$container" -- dillo --version; then
  printf 'ERROR: dillo not installed\n' >&2
  exit 1
fi

buildah commit "$container" dillo
