#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    dbus-x11 \
    dunst \
    dunstify

buildah config \
  --cmd '[]' \
  --entrypoint '["dunst"]' \
  "$container"

buildah copy "$container" config/dunstrc /root/.config/dunst/

if ! buildah run -t "$container" -- dunst --version; then
  printf 'ERROR: dunst not installed\n' >&2
  exit 1
fi

buildah commit "$container" dunst
