#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    buildah \
    fuse-overlayfs

# enable readonly image fuse mounting from additional container store
buildah run "$container" -- \
  sed -i \
    -e 's|^#mount_program|mount_program|g' \
    -e '/additionalimage.*/a "/var/lib/shared",' \
    /etc/containers/storage.conf

# create empty container image store to keep buildah from complaining if we
# don't volume mount an additional container store
buildah run "$container" -- sh <<'EOF'
mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers
touch /var/lib/shared/overlay-images/images.lock
touch /var/lib/shared/overlay-layers/layers.lock
EOF

# set buildah isolation to use chroot instead of using its own namespace based
# separation so that the container doesn't need SYS_ADMIN capabilities
buildah config \
  --cmd '[]' \
  --entrypoint '["buildah"]' \
  --env _BUILDAH_STARTED_IN_USERNS="" \
  --env BUILDAH_ISOLATION=chroot \
  "$container"

if ! buildah run -t "$container" -- buildah version; then
  printf 'ERROR: buildah not installed\n' >&2
  exit 1
fi

buildah commit "$container" localhost/buildah
