#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    mc \
    openssh-client

buildah run "$container" -- \
  wget -qO /usr/share/mc/skins/dracula.ini \
    https://raw.githubusercontent.com/dracula/midnight-commander/master/skins/dracula.ini

buildah config \
  --cmd '[]' \
  --env MC_SKIN=dracula \
  --entrypoint '["mc"]' \
  "$container"

if ! buildah run -t "$container" -- mc --version; then
  printf 'ERROR: mc not installed\n' >&2
  exit 1
fi

buildah commit "$container" mc
