#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    eza \
    file

buildah config \
  --cmd '[]' \
  --entrypoint '["eza"]' \
  "$container"

if ! buildah run -t "$container" -- eza --version; then
  printf 'ERROR: eza not installed\n' >&2
  exit 1
fi

buildah commit "$container" eza
