#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    jq

buildah config \
  --cmd '[]' \
  --entrypoint '["jq"]' \
  "$container"

if ! buildah run -t "$container" -- jq --version; then
  printf 'ERROR: jq not installed\n' >&2
  exit 1
fi

buildah commit "$container" jq
