#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    fontforge \
    fontforge-gui

buildah config \
  --cmd '[]' \
  --entrypoint '["fontforge"]' \
  "$container"

if ! buildah run -t "$container" -- fontforge -version; then
  printf 'ERROR: fontforge not installed\n' >&2
  exit 1
fi

buildah commit "$container" fontforge
