#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    chafa

buildah config \
  --cmd '[]' \
  --entrypoint '["chafa"]' \
  "$container"

if ! buildah run -t "$container" -- chafa --version; then
  printf 'ERROR: chafa not installed\n' >&2
  exit 1
fi

buildah commit "$container" chafa
