#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    gnupg \
    isync \
    less \
    mblaze \
    mblaze-crypto \
    notmuch \
    openssl

buildah copy "$container" config /root
buildah copy "$container" scripts /usr/local/bin

buildah config \
  --cmd '[]' \
  --entrypoint '["mbsync"]' \
  --env MBLAZE=/root/mail/.mblaze \
  "$container"

for i in gpg mbsync notmuch
do
  if ! buildah run -t "$container" -- "$i" --version >/dev/null
  then
    printf 'ERROR: %s not installed\n' "$i" >&2
    exit 1
  fi
done

if ! buildah run -t "$container" -- openssl version >/dev/null
then
  printf 'ERROR: openssl not installed\n' >&2
  exit 1
fi

if ! buildah run -t "$container" -- /bin/sh -c 'command -v sendmail' >/dev/null
then
  printf 'ERROR: sendmail not installed\n' >&2
  exit 1
fi

buildah commit "$container" isync
