#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    aspell \
    aspell-en

buildah config \
  --cmd '[]' \
  --entrypoint '["aspell"]' \
  "$container"

if ! buildah run -t "$container" -- aspell --version; then
  printf 'ERROR: aspell not installed\n' >&2
  exit 1
fi

buildah commit "$container" aspell
