#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    skopeo

buildah config \
  --cmd '[]' \
  --entrypoint '["skopeo"]' \
  "$container"

if ! buildah run -t "$container" -- skopeo --version; then
  printf 'ERROR: skopeo not installed\n' >&2
  exit 1
fi

buildah commit "$container" localhost/skopeo
