#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    shellcheck

buildah config \
  --cmd '[]' \
  --entrypoint '["shellcheck"]' \
  "$container"

if ! buildah run -t "$container" -- shellcheck --version; then
  printf 'ERROR: shellcheck not installed\n' >&2
  exit 1
fi

buildah commit "$container" shellcheck
