#!/bin/sh

src=https://2ton.com.au/standalone_binaries/toplip
path=/usr/bin/toplip
chksum_url=https://2ton.com.au/Products

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah copy --chmod 755 "$container" "$src" "$path"

if ! buildah run "$container" -- sh -c "test \
  \$(sha256sum $path | cut -d ' ' -f 1) = \
  \$(wget -qO - $chksum_url | grep -A 2 $src | grep -oE '[0-9a-f]{64}')"
then
  printf 'ERROR: sha256 sums do NOT match!\n' >&2
  exit 1
fi

buildah config \
  --env PS1='\[\e[34m\]toplip>\[\e[0m\] ' \
  "$container"

buildah commit "$container" toplip
