#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    ledger

buildah config \
  --cmd '[]' \
  --entrypoint '["ledger"]' \
  "$container"

if ! buildah run -t "$container" -- ledger --version; then
  printf 'ERROR: ledger not installed\n' >&2
  exit 1
fi

buildah commit "$container" ledger
