#!/bin/sh

container=$(buildah from --pull debian:stable-slim)
keyring=brave-browser-archive-keyring.gpg

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  sh -c 'apt update && apt install --yes wget'

buildah run "$container" -- \
  wget --no-verbose \
    --output-document /usr/share/keyrings/"$keyring" \
    https://brave-browser-apt-release.s3.brave.com/"$keyring"

buildah run "$container" -- \
  sh -c "printf 'deb [signed-by=/usr/share/keyrings/%s] %s stable main\n' \
    $keyring https://brave-browser-apt-release.s3.brave.com/ | \
    tee /etc/apt/sources.list.d/brave-browser-release.list"

buildah run "$container" -- \
  sh -c 'apt update && \
    apt install --no-install-recommends --yes \
      brave-browser \
      libgl1-mesa-dri \
      libgl1-mesa-glx \
      libpulse0 && \
    rm -rf /var/lib/apt/lists/*'

buildah run "$container" -- \
  useradd -ms /bin/bash -G audio,video braveuser

buildah config \
  --cmd '[]' \
  --entrypoint '["brave-browser"]' \
  --user braveuser \
  "$container"

buildah commit "$container" brave
