#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    gimp

buildah config \
  --cmd '[]' \
  --entrypoint '["gimp"]' \
  "$container"

if buildah run -t "$container" -- gimp --version; then
  buildah commit "$container" gimp
fi
