#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    ruby \
    ruby-rdoc

buildah run "$container" -- \
  gem install --prerelease \
    asciidoctor \
    asciidoctor-pdf \
    rouge

buildah config \
  --cmd '[]' \
  --entrypoint '["asciidoctor"]' \
  "$container"

if ! buildah run -t "$container" -- asciidoctor --version; then
  printf 'ERROR: asciidoctor not installed\n' >&2
  exit 1
fi

buildah commit "$container" asciidoctor
