[[language]]
name = "css"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "css"] }

[[language]]
name = "graphql"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "graphql"] }

[[language]]
name = "html"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "html"] }

[[language]]
name = "javascript"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "json"] }

[[language]]
name = "markdown"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "markdown"] }

[[language]]
name = "scss"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "scss"] }

[[language]]
name = "typescript"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "typescript"] }

[[language]]
name = "vue"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "vue"] }

[[language]]
name = "yaml"
formatter = { command = 'pnpm', args = ["exec", "prettier", "--parser", "yaml"] }
