#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    bat \
    file \
    fzf \
    vis

buildah copy "$container" ../bat/config /root/.config/bat
buildah copy "$container" config /root/.config/vis

buildah config \
  --cmd '[]' \
  --entrypoint '["vis"]' \
  "$container"

if ! buildah run -t "$container" -- vis -v; then
  printf 'ERROR: vis not installed\n' >&2
  exit 1
fi

buildah commit "$container" vis
