#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache ripgrep

buildah config \
  --cmd '[]' \
  --entrypoint '["rg"]' \
  "$container"

if ! buildah run -t "$container" -- rg --version; then
  printf 'ERROR: rg not installed\n' >&2
  exit 1
fi

buildah commit "$container" rg
