#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" \
  apk add --no-cache \
    imagemagick

buildah config \
  --cmd '[]' \
  --entrypoint '["magick"]' \
  "$container"

if ! buildah run -t "$container" -- magick -version; then
  printf 'ERROR: imagemagick not installed\n' >&2
  exit 1
fi

buildah commit "$container" imagemagick
