#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    ca-certificates \
    ffmpeg \
    firefox \
    hicolor-icon-theme \
    hunspell \
    hunspell-en \
    libpulse \
    mesa-demos \
    mesa-dri-gallium \
    pciutils-dev

buildah config \
  --cmd '[]' \
  --entrypoint '["firefox"]' \
  --env GTK_THEME=Adwaita:dark \
  --env TZ=UTC \
  "$container"

if ! buildah run -t "$container" -- firefox --version; then
  printf 'ERROR: firefox not installed\n' >&2
  exit 1
fi

buildah commit "$container" firefox
