#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    transmission-daemon

buildah config \
  --cmd '[]' \
  --entrypoint '["transmission-daemon"]' \
  "$container"

if ! buildah run -t "$container" -- transmission-daemon --version; then
  printf 'ERROR: transmission-daemon not installed\n' >&2
  exit 1
fi

buildah commit "$container" transmission-daemon
