#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    bmon

buildah config \
  --cmd '[]' \
  --entrypoint '["bmon"]' \
  "$container"

if ! buildah run -t "$container" -- bmon -V; then
  printf 'ERROR: bmon not installed\n' >&2
  exit 1
fi

buildah commit "$container" bmon
