#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    tmux

buildah copy "$container" config/tmux.conf /root/.config/tmux/tmux.conf

buildah config \
  --cmd '[]' \
  --entrypoint '["/bin/sh", "-lc", "tmux new-session -s $HOSTNAME"]' \
  --env LANG=en_US.UTF-8 \
  "$container"

if ! buildah run -t "$container" -- tmux -V; then
  printf 'ERROR: tmux not installed\n' >&2
  exit 1
fi

buildah commit "$container" tmux
