#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    inkscape

buildah config \
  --cmd '[]' \
  --entrypoint '["inkscape"]' \
  "$container"

if buildah run -t "$container" -- inkscape --version; then
  buildah commit "$container" inkscape
fi
