#!/bin/sh

build=$(buildah from --pull keybaseio/client)
container=$(buildah from --pull debian:stable-slim)

mnt=$(buildah mount "$build")

trap 'buildah umount "$build" && buildah rm "$build" "$container"' EXIT INT TERM

# copy keybase binaries into the container
for binary in keybase kbfsfuse git-remote-keybase; do
  buildah copy "$container" "$mnt/usr/bin/$binary" "/usr/bin/$binary"
  buildah copy "$container" "$mnt/usr/bin/$binary.sig" "/usr/bin/$binary.sig"
done

# configure the container entrypoint
buildah copy "$container" entrypoint.sh /usr/bin/entrypoint.sh
buildah run "$container" -- chmod +x /usr/bin/entrypoint.sh

# add `git` for `keybase git` support
buildah run "$container" -- \
  sh -c 'apt update && \
    apt install --no-install-recommends --yes \
      git && \
    rm -rf /var/lib/apt/lists/*'

buildah config \
  --cmd '[]' \
  --entrypoint '["entrypoint.sh"]' \
  --env KEYBASE_ALLOW_ROOT=1 \
  "$container"

if ! buildah run --tty "$container" -- keybase version; then
  printf 'ERROR: keybase not installed\n' >&2
  exit 1
fi

buildah commit "$container" keybase
