#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    curl

buildah config \
  --cmd '[]' \
  --entrypoint '["curl"]' \
  "$container"

if ! buildah run -t "$container" -- curl --version; then
  printf 'ERROR: curl not installed\n' >&2
  exit 1
fi

buildah commit "$container" curl
