#!/bin/sh

container=$(buildah from --pull alpine:edge)

trap 'buildah rm "$container"' EXIT INT TERM

buildah run "$container" -- \
  apk add --no-cache \
    hunspell \
    hunspell-en-us

buildah config \
  --cmd '[]' \
  --entrypoint '["hunspell"]' \
  "$container"

if ! buildah run -t "$container" -- hunspell --version; then
  printf 'ERROR: hunspell not installed\n' >&2
  exit 1
fi

buildah commit "$container" hunspell
